# Generated by Django 2.2.11 on 2020-03-21 09:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DHT22',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sensors.BaseModel')),
                ('temperature', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-50.0), django.core.validators.MaxValueValidator(100.0)])),
                ('humidity', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('filtered_temperature', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-50.0), django.core.validators.MaxValueValidator(100.0)])),
                ('filtered_humidity', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
            ],
            bases=('sensors.basemodel',),
        ),
    ]
