# Generated by Django 2.2.11 on 2020-03-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht22',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
