# Generated by Django 2.2.11 on 2020-03-20 14:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_dht22_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dht22',
            name='filtered_humidity',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='dht22',
            name='filtered_temperature',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(-50.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
